import { Resend } from 'resend';
import { NextResponse } from 'next/server';

import { CONTACT_INFO } from '@/lib/config';  

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(request: Request) {
  try {
    const { name, email, message } = await request.json();

    // Validation basique
    if (!name || !email || !message) {
      return NextResponse.json({ error: "Missing fields" }, { status: 400 });
    }

    const data = await resend.emails.send({
      
      from: 'Contact form <onboarding@resend.dev>', 
      to: CONTACT_INFO.email, 
      replyTo: email,
      subject: `🌍 New Tour Inquiry: ${name}`,
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden;">
          <div style="background-color: #059669; padding: 20px; text-align: center;">
            <h1 style="color: white; margin: 0; font-size: 24px;">New Customer Inquiry</h1>
          </div>
          <div style="padding: 30px; background-color: #ffffff;">
            <p style="font-size: 16px; color: #475569;">You have received a new message from your website contact form:</p>
            <div style="background-color: #f8fafc; padding: 20px; border-radius: 8px; margin-top: 20px;">
              <p style="margin: 0 0 10px 0;"><strong>👤 Name:</strong> ${name}</p>
              <p style="margin: 0 0 10px 0;"><strong>✉️ Email:</strong> <a href="mailto:${email}" style="color: #059669; text-decoration: none;">${email}</a></p>
              <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 15px 0;">
              <p style="margin: 0;"><strong>💬 Message:</strong></p>
              <p style="color: #1e293b; line-height: 1.6; font-style: italic; margin-top: 10px;">
                "${message.replace(/\n/g, '<br>')}"
              </p>
            </div>
            <div style="margin-top: 30px; text-align: center;">
              <a href="mailto:${email}" style="background-color: #059669; color: white; padding: 12px 24px; border-radius: 6px; text-decoration: none; font-weight: bold; display: inline-block;">
                Reply to Client
              </a>
            </div>
          </div>
          <div style="background-color: #f1f5f9; padding: 15px; text-align: center; font-size: 12px; color: #64748b;">
            This email was automatically generated by your website's contact form.
          </div>
        </div>
      `
    });

    return NextResponse.json({ success: true, data });
  } catch (error) {
    console.error("Resend Error:", error);
    return NextResponse.json({ success: false, error: "Internal Server Error" }, { status: 500 });
  }
}